# Generated by Django 5.1.4 on 2024-12-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('captain', models.CharField(max_length=50)),
                ('team_photo', models.ImageField(blank=True, null=True, upload_to='imgs')),
                ('status', models.CharField(blank=True, choices=[('Full team', 'Full team'), ('Available team', 'Available team')], max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_app.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
