# Generated by Django 5.1.4 on 2024-12-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_team_delete_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='category',
            new_name='type',
        ),
        migrations.AddField(
            model_name='team',
            name='players_no',
            field=models.IntegerField(default=0),
        ),
    ]
