# Generated by Django 5.1.4 on 2024-12-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_revenue_total_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
