# Generated by Django 5.1.4 on 2024-12-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
